#!/usr/bin/env bash
set -e

CWD=`dirname $0`
CONTRACTS=$CWD/../../contracts
LIB=$CWD/../lib

mkdir -p $CONTRACTS/abi/dai/v1/
rm -f $CONTRACTS/abi/dai/v1/*.json
cp $LIB/sai/out/addresses.json $CONTRACTS/abi/dai/v1/
cp $LIB/sai/out/*.abi $CONTRACTS/abi/dai/v1/
cd $CONTRACTS/abi/dai/v1
for file in *.abi; do
    mv "$file" "$(basename "$file" .abi).json"
done
rm -f *Test*.json *Fab.json Dev*.json
cd -

# Copy DSProxy ABI into project
mkdir -p $CONTRACTS/abi/dsProxy/
cp $LIB/ds-proxy/out/DSProxy.abi $CONTRACTS/abi/dsProxy/v1.json

# Copy DSProxyFactory ABI into project
mkdir -p $CONTRACTS/abi/dsProxyFactory/
cp $LIB/ds-proxy/out/DSProxyFactory.abi $CONTRACTS/abi/dsProxyFactory/v1.json

# Copy SaiProxyCreateAndExecute ABI into project
mkdir -p $CONTRACTS/abi/saiProxy/
cp $LIB/sai-proxy/out/SaiProxyCreateAndExecute.abi $CONTRACTS/abi/saiProxy/v1.json

# Copy ProxyRegistry ABI into project
mkdir -p $CONTRACTS/abi/proxyRegistry/
cp $LIB/proxy-registry/out/ProxyRegistry.abi $CONTRACTS/abi/proxyRegistry/v1.json
