#!/usr/bin/env bash
## This script is invoked like
##
##   $ with-deployed-system node index.js
##
## which will run Node in the environment of a running Geth testnet
## with the Sai system deployed.
##
## The environment has ETH_RPC_URL set along with the contract addresses.
##
## When the script exits, the Geth testnet is stopped and deleted.

set -ex

# Start a local testnet on port 2000; set to stop on exit.
./node_modules/.bin/ganache-cli -i 999 -p 2000 -a 1000 -m "hill law jazz limb penalty escape public dish stand bracket blue jar" >/dev/null & netpid=$!
trap "kill $netpid" EXIT

# Wait until it's up, then use it for the deployment.
export ETH_RPC_URL=http://127.1:2000
until curl -s "$ETH_RPC_URL"; do sleep 2; done

# Use the Sai system's deploy scripts to start it.
cd lib/sai
export SETH_STATUS=yes
export ETH_RPC_ACCOUNTS=yes # Don't use ethsign
bin/deploy-fab && . load-fab-unknown
bin/deploy     && . load-env-unknown
cd ../..

# We now have SAI_GEM, SAI_SAI, SAI_SKR, etc in the environment.
# See the list at the bottom of the in the deploy script.
# Proceed to the command given as arguments.
"$@"
