module.exports = {
  TUB: require('./abis/SaiTub'),
  MCD_END_1: require('./abis/End'),
  MCD_VAT_1: require('./abis/Vat'),
  GET_CDPS_1: require('./abis/GetCdps'),
  CDP_MANAGER_1: require('./abis/DssCdpManager'),
  MCD_DAI_1: require('./abis/Dai'),
  MCD_POT_1: require('./abis/Pot'),
  REDEEMER: require('./abis/Redeemer'),
  MIGRATION: require('./abis/ScdMcdMigration'),
  MIGRATION_PROXY_ACTIONS: require('./abis/MigrationProxyActions'),
  OLD_CHIEF: require('./abis/DSChief'),
  OLD_VOTE_PROXY_FACTORY: require('./abis/VoteProxyFactory'),
  'MCD_JOIN_*': require('./abis/GemJoin'),
  PROXY_ACTIONS_END: require('./abis/DssProxyActionsEnd'),
  SAI_CAGEFREE: require('./abis/CageFree'),
  MCD_ESM: require('./abis/ESM'),
  MCD_END: require('./abis/End'),
  MCD_VAT: require('./abis/Vat'),
  GET_CDPS: require('./abis/GetCdps'),
  CDP_MANAGER: require('./abis/DssCdpManager'),
  MCD_DAI: require('./abis/Dai'),
  MCD_POT: require('./abis/Pot')
};
