export const MCD_DOG = 'MCD_DOG';
export const MCD_CLIP_AAVE_A = 'MCD_CLIP_AAVE_A';
export const MCD_CLIP_BAL_A = 'MCD_CLIP_BAL_A';
export const MCD_CLIP_BAT_A = 'MCD_CLIP_BAT_A';
export const MCD_CLIP_COMP_A = 'MCD_CLIP_COMP_A';
export const MCD_CLIP_ETH_A = 'MCD_CLIP_ETH_A';
export const MCD_CLIP_ETH_B = 'MCD_CLIP_ETH_B';
export const MCD_CLIP_ETH_C = 'MCD_CLIP_ETH_C';
export const MCD_CLIP_KNC_A = 'MCD_CLIP_KNC_A';
export const MCD_CLIP_LINK_A = 'MCD_CLIP_LINK_A';
export const MCD_CLIP_LRC_A = 'MCD_CLIP_LRC_A';
export const MCD_CLIP_MANA_A = 'MCD_CLIP_MANA_A';
export const MCD_CLIP_RENBTC_A = 'MCD_CLIP_RENBTC_A';
export const MCD_CLIP_UNI_A = 'MCD_CLIP_UNI_A';
export const MCD_CLIP_WBTC_A = 'MCD_CLIP_WBTC_A';
export const MCD_CLIP_YFI_A = 'MCD_CLIP_YFI_A';
export const MCD_CLIP_ZRX_A = 'MCD_CLIP_ZRX_A';
export const MCD_CLIP_UNIV2DAIETH_A = 'MCD_CLIP_UNIV2DAIETH_A';
export const MCD_CLIP_UNIV2USDCETH_A = 'MCD_CLIP_UNIV2USDCETH_A';
export const MCD_CLIP_UNIV2ETHUSDT_A = 'MCD_CLIP_UNIV2ETHUSDT_A';
export const MCD_CLIP_UNIV2WBTCDAI_A = 'MCD_CLIP_UNIV2WBTCDAI_A';
export const MCD_CLIP_UNIV2WBTCETH_A = 'MCD_CLIP_UNIV2WBTCETH_A';
export const MCD_CLIP_UNIV2LINKETH_A = 'MCD_CLIP_UNIV2LINKETH_A';
export const MCD_CLIP_UNIV2UNIETH_A = 'MCD_CLIP_UNIV2UNIETH_A';
export const MCD_CLIP_UNIV2AAVEETH_A = 'MCD_CLIP_UNIV2AAVEETH_A';
export const MCD_CLIP_UNIV2DAIUSDT_A = 'MCD_CLIP_UNIV2DAIUSDT_A';
export const MCD_CLIP_UNIV2DAIUSDC_A = 'MCD_CLIP_UNIV2DAIUSDC_A';
export const MCD_CLIP_USDC_A = 'MCD_CLIP_USDC_A';
export const MCD_CLIP_USDC_B = 'MCD_CLIP_USDC_B';
export const MCD_CLIP_TUSD_A = 'MCD_CLIP_TUSD_A';
export const MCD_CLIP_PAXUSD_A = 'MCD_CLIP_PAXUSD_A';
export const MCD_CLIP_GUSD_A = 'MCD_CLIP_GUSD_A';
export const MCD_CLIP_USDT_A = 'MCD_CLIP_USDT_A';

export const ALL_CLIPS = [
  MCD_CLIP_AAVE_A,
  MCD_CLIP_BAL_A,
  MCD_CLIP_BAT_A,
  MCD_CLIP_COMP_A,
  MCD_CLIP_ETH_A,
  MCD_CLIP_ETH_B,
  MCD_CLIP_ETH_C,
  MCD_CLIP_KNC_A,
  MCD_CLIP_LINK_A,
  MCD_CLIP_LRC_A,
  MCD_CLIP_MANA_A,
  MCD_CLIP_RENBTC_A,
  MCD_CLIP_UNI_A,
  MCD_CLIP_WBTC_A,
  MCD_CLIP_YFI_A,
  MCD_CLIP_ZRX_A,
  MCD_CLIP_UNIV2DAIETH_A,
  MCD_CLIP_UNIV2USDCETH_A,
  MCD_CLIP_UNIV2ETHUSDT_A,
  MCD_CLIP_UNIV2WBTCDAI_A,
  MCD_CLIP_UNIV2WBTCETH_A,
  MCD_CLIP_UNIV2LINKETH_A,
  MCD_CLIP_UNIV2UNIETH_A,
  MCD_CLIP_UNIV2AAVEETH_A,
  MCD_CLIP_UNIV2DAIUSDT_A,
  MCD_CLIP_UNIV2DAIUSDC_A,
  MCD_CLIP_USDC_A,
  MCD_CLIP_USDC_B,
  MCD_CLIP_TUSD_A,
  MCD_CLIP_PAXUSD_A,
  MCD_CLIP_GUSD_A,
  MCD_CLIP_USDT_A
];
