export default {
  SAI_PIP: 'SAI_PIP',
  SAI_PEP: 'SAI_PEP',
  SAI_PIT: 'SAI_PIT',
  SAI_SIN: 'SAI_SIN',
  SAI_MOM: 'SAI_MOM',
  SAI_VOX: 'SAI_VOX',
  SAI_TUB: 'SAI_TUB',
  SAI_TAP: 'SAI_TAP',
  SAI_TOP: 'SAI_TOP',
  SAI_PROXY: 'SAI_PROXY',
  PROXY_REGISTRY: 'PROXY_REGISTRY',
  DS_PROXY_FACTORY: 'DS_PROXY_FACTORY',
  DS_PROXY: 'DS_PROXY',
  MULTICALL: 'MULTICALL'
};
