const enums = {
  SAI_PIP: 'SAI_PIP',
  SAI_PEP: 'SAI_PEP',
  SAI_PIT: 'SAI_PIT',
  SAI_SIN: 'SAI_SIN',
  SAI_DAD: 'SAI_DAD',
  SAI_MOM: 'SAI_MOM',
  SAI_VOX: 'SAI_VOX',
  SAI_TUB: 'SAI_TUB',
  SAI_TAP: 'SAI_TAP',
  SAI_TOP: 'SAI_TOP',
  MAKER_OTC: 'MAKER_OTC',
  ZERO_EX_EXCHANGE: 'ZERO_EX_EXCHANGE'
};
export default enums;
